[package]
name = "processtree-rust"
version = "0.2.0"
authors = ["Konstantin Läufer <klaeufer@gmail.com>"]

[[bin]]
name = "fakeps"

[[bin]]
name = "processtree"

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
rand = "0.8.5"
